management.security.enabled: false
security.basic.enabled: false

server:
    port: <%= port %>

spring:
    profiles:
        active: prod
    cloud:
        stream:
            kafka:
                binder:
                    zkNodes: <%= zookeeperurl %>
                    brokers: <%= kafkaurl %>
    
metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: <%= baseName %>
