platform: linux

image_resource:
  type: docker-image
  source: {repository: niaquinto/gradle}

inputs:
  - name: resource-<%= baseName %>

outputs:
  - name: resource-jar

run:
  path: ./resource-<%= baseName %>/ci/scripts/package.sh

